### PR TITLE
Updated version number

### PR DESCRIPTION
**Pull request by rkosafo**
Updated assembly version to match nuget version

### CODE REVIEW

**Comment by rspeele** [comment]
Hey,

So this applies to both this PR and the one for FParsec-Pipes.

We need to make the assembly version match the version that the NuGet packages will be bumped to, rather than the current version, since the end goal is to release new stuff on NuGet to make Rezoom.SQL work out of the box.

Back a couple years ago, you could have a .nuspec file that would set the NuGet pkg version to $version$ so it would automatically match the version in AssemblyInfo. That would be ideal, so the two don't have to be kept in sync manually going forward.

But for the time being, it would also be OK to just bump the version to 1.0.1 here and 1.1.1 in Pipes, and make sure it is changed both in AssemblyInfo and in the fsproj. At least, in FParsec-Pipes it is specified in the fsproj -- kkm000 did some work in [this PR](https://github.com/rspeele/FParsec-Pipes/pull/10) for that. Not sure if it is necessary to replicate that work here. I am going to go ahead and fix up the versions in the FParsec-Pipes repo since it seems quite clear how to proceed there.

Would you be interested in having direct push access to Rezoom and Rezoom.SQL?

**Comment by rkosafo** [comment]
Hi,
Noted. I'll bump up the version.

In my case, I just replaced the dlls in the .nuget folder after building :)

In the referenced PR, the library was updated to support 4.5 and .NET Standard 1.6. What is the minimum .NET Standard version you are looking since the others are 2.0?

Yes. I'll be interested in direct push access.

**Comment by rspeele** [comment]
I went ahead and pushed a new NuGet package for FParsec-Pipes where both the pkg version and assembly version are 1.1.1.

You should also have received an invitation to collaborate both here and on Rezoom.SQL.

Regarding the .NET Standard version, I think Rezoom and Rezoom.SQL can target 2.0. For Pipes, the target was lowered to 1.6 because it is supposed to be a generally useful extension to FParsec and therefore shouldn't have higher requirements than the base library.

**Comment by rkosafo** [comment]
@rspeele With the version updated, can you create the new nuget packages so Rezoom.SQL takes a dependency on 1.1.1?

**Pull request merged**
